- hosts: hadoop
  tasks:
    - copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - { src: '/opt/share/playbook/.bashrc', dest: '/root/.bashrc' }
        - { src: '/opt/share/playbook/etc/hosts', dest: '/etc/hosts' }

    - block:
      - name: "Checking folders"
        stat:
         path: "{{item}}"
        register: folder_stats
        with_items:
        - ["/opt/hadoop/data"]
      - name: "Creating multiple folders without disturbing previous permissions"
        file:
         path: "{{item.item}}"
         state: directory
         mode: 0755
         group: root
         owner: root
        when: item.stat.exists == false
        with_items:
        - "{{folder_stats.results}}"
